=== drapejny/java_epam/Task2/src/main/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns:tns="http://www.example.com/flowers"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
        <sequence>
            <element name="visual-aspect" type="tns:VisualAspect"/>
            <element name="soil" type="tns:Soil"/>
            <element name="growing-temperature" type="int"/>
            <element name="is-light-loving" type="boolean"/>
            <element name="watering" type="int"/>
            <element name="multiplying" type="tns:Multiplying"/>
        </sequence>
        <attribute name="name" type="tns:Name" use="required"/>
        <attribute name="origin" type="string" use="optional"/>
    </complexType>

    <complexType name="AnnualFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="flowering-period" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PerennualFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="is-wintering" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="VisualAspect">
        <sequence>
            <element name="size" type="int"/>
            <element name="leaves-color" type="string"/>
            <element name="blossom-color" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="PODZOLIC"/>
            <enumeration value="GROUND"/>
            <enumeration value="SOD_PODZOLIC"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="BY_LEAVES"/>
            <enumeration value="BY_STALK"/>
            <enumeration value="BY_SEED"/>
        </restriction>
    </simpleType>

    <simpleType name="Name">
        <restriction base="ID"/>
    </simpleType>
    
    <element name="flower" type="tns:Flower" abstract="true"/>
    <element name="annual-flower" type="tns:AnnualFlower" substitutionGroup="tns:flower"/>
    <element name="perennual-flower" type="tns:PerennualFlower" substitutionGroup="tns:flower"/>
</schema>

=== drapejny/java_epam/Task2/src/main/resources/flowers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsd:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <annual-flower name="Marigolds" origin="Africa">
        <visual-aspect>
            <size>20</size>
            <leaves-color>Green</leaves-color>
            <blossom-color>Orange</blossom-color>
        </visual-aspect>
        <soil>GROUND</soil>
        <growing-temperature>27</growing-temperature>
        <is-light-loving>true</is-light-loving>
        <watering>30</watering>
        <multiplying>BY_SEED</multiplying>
        <flowering-period>MAY</flowering-period>
    </annual-flower>

    <perennual-flower name="Asters" origin="China">
        <visual-aspect>
            <size>25</size>
            <leaves-color>Green</leaves-color>
            <blossom-color>Red</blossom-color>
        </visual-aspect>
        <soil>GROUND</soil>
        <growing-temperature>28</growing-temperature>
        <is-light-loving>false</is-light-loving>
        <watering>40</watering>
        <multiplying>BY_LEAVES</multiplying>
        <is-wintering>true</is-wintering>
    </perennual-flower>
</flowers>
